@startuml
class MainPage <<partial>> {
    + MainPage()
    # <<override>> OnNavigatedTo(args:NavigatedToEventArgs) : void
    <<internal>> OnPanUpdated(sender:object?, e:PanUpdatedEventArgs) : void
    - MainPage_SizeChanged(sender:object?, e:EventArgs) : void
    + {static} GenerateCard() : void
    + {static} ZIndexMove(touchCard:GraphicsView) : void
}
class CurrentTable <<static>> {
    + {static} TableDictionary : Dictionary<int, Table>
    + {static} GenerateCardCount : int <<get>>
    + {static} FlashCardDictionary : Dictionary<FlashCardGuid, FlashCard> <<get>>
    + {static} ChangeTable(tableId:int) : void
}
class Table {
    + Id : Guid <<get>>
    + GenerateCardCount : int <<get>> = 0
    + RootCardCount : int <<get>>
    + RootList : List<FlashCard> <<get>>
    + FlashCardDictionary : Dictionary<FlashCardGuid, FlashCard>
    + Table(parent:Grid)
    + RootIdRegenerate() : void
    + <<override>> GetHashCode() : int
    + Equals(other:Table?) : bool
}
class FlashCardFactory <<static>> {
    + {static} GererateCard() : FlashCard
    {static} - GenerateTextBox(graph:GraphicsView, property:FlashCardProperty) : Editor
}
class FlashCardProperty {
    + CardHeight : float <<get>> <<set>> = 150f
    + CardWidth : float <<get>> <<set>> = 350f
    + CardBackgroundColor : Color <<get>> <<set>>
    + TextBoxHeight : float <<get>> <<set>> = 110f
    + TextBoxWidth : float <<get>> <<set>> = 300f
    + TextFontSize : int <<get>> <<set>> = 16
    + TextFontColor : Color <<get>> <<set>>
    + TextBoxBackGround : Color <<get>> <<set>>
    + TagHeight : float <<get>> <<set>> = 44f
    + TagWidth : float <<get>> <<set>> = 80f
    + TagFontSize : int <<get>> <<set>> = 10
    + TagFontColor : Color <<get>> <<set>>
    + TagBackGround : Color <<get>> <<set>>
    + FlashCardProperty()
}
class FlashCardGuid {
    + id : Guid
    + {static} FlashCardGuidKeyDict : ConditionalWeakTable<GraphicsView, FlashCardGuid>
    + FlashCardGuid(_id:Guid)
}
class FlashCard {
    + RootId : int <<get>>
    + IsRoot : bool <<get>>
    + TranslationX : double <<get>>
    + TranslationY : double <<get>>
    + ZIndex : List<ViewIndexPair> <<get>>
    + FlashCard(cardObject:CardObject, tag:Tag)
    + MoveTop() : void
    + MoveLower() : void
    - CalcZIndex() : void
    + GetViewModel() : List<IView>
    + Translation(nextX:double, nextY:double) : void
    - GenerateKey() : void
}
class CardObject {
    + Id : Guid <<get>>
    + TranslationX : double <<get>> <<set>>
    + TranslationY : double <<get>> <<set>>
    + CardObject(_view:GraphicsView, _editor:Editor, _property:FlashCardProperty)
    + Translation(nextX:double, nextY:double) : void
    + Equals(other:CardObject?) : bool
    + <<override>> GetHashCode() : int
}
class Tag {
    + Id : Guid <<get>>
    + RootId : int <<get>> <<set>>
    + IsRoot : bool <<get>>
    - tagString : string <<get>>
    <<const>> - TAG_PADDING_Y : double = 5d
    <<const>> - LABEL_PADDING_Y : double
    + TranslationX : double <<get>> <<set>>
    + TranslationY : double <<get>> <<set>>
    - _children : List<Tag>
    + Children : List<Tag> <<get>>
    + Tag(cobj:CardObject, property:FlashCardProperty)
    + GenerateLabel(card:CardObject) : Label
    + Reload() : void
    + Traverse() : IEnumerable<Tag>
    + Translation(Cobj:CardObject) : void
    + GetTagId() : string
    + ChangeRoot(newParent:Tag?, newId:int) : Tag?
    + MoveIdInChildren(newId:int) : void
    + ResetRootId() : void
    + RemoveChild(target:Tag) : bool
    + Equals(other:Tag?) : bool
    + <<override>> GetHashCode() : int
}
class DraggableGraphics {
    - _corner : float = 7f
    - _cornerTag : float = 7f
    - IsCard : bool = true
    + DraggableGraphics(_property:FlashCardProperty, parent:GraphicsView, isCard:bool)
    + Draw(canvas:ICanvas, dirtyRect:RectF) : void
}
class Anchor {
    + StartX : double
    + StartY : double
    + Anchor(_x:double, _y:double)
}
class "IEquatable`1"<T> {
}
class ViewIndexPair {
    + Index : int <<get>> <<internal set>>
    + ViewModel : View <<get>>
    + ViewIndexPair(index:int, viewModel:View)
}
ContentPage <|-- MainPage
MainPage o-> "Instance" MainPage
MainPage --> "_dragAnchor" Anchor
CurrentTable o-> "table" Table
CurrentTable --> "MainPageContent" Grid
"IEquatable`1" "<Table>" <|-- Table
Table --> "ParentGrid" Grid
FlashCardFactory --> "MainPage" MainPage
FlashCard o-> "CardObject" CardObject
FlashCard o-> "Tag" Tag
FlashCard --> "guid" Guid
"IEquatable`1" "<CardObject>" <|-- CardObject
CardObject --> "Background" GraphicsView
CardObject --> "Textbox" Editor
CardObject --> "Property" FlashCardProperty
"IEquatable`1" "<Tag>" <|-- Tag
Tag o-> "CardObject" CardObject
Tag o-> "Background" GraphicsView
Tag o-> "Label" Label
Tag o-> "Property" FlashCardProperty
Tag --> "Parent" Tag
IDrawable <|-- DraggableGraphics
DraggableGraphics --> "parentView" GraphicsView
DraggableGraphics --> "property" FlashCardProperty
FlashCard +-- ViewIndexPair
@enduml
